export const MOBILE_MODE_WIDTH = 400
export const SIDE_BAR_WIDTH_RATIO = 25
export const MOBILE_HEADER_BAR_HEIGHT = 50
export const SMALL_WINDOW_WIDTH = 600
export const MEDIUM_WINDOW_WIDTH = 800
export const LARGE_WINDOW_WIDTH = 1000
